[<img src="https://colab.research.google.com/assets/colab-badge.svg\">](https://colab.research.google.com/drive/1DeK9UcoShNYAaGZZzXCd2FYRZB_CtIl7?usp=sharing)

# Câu hỏi tự luận

## 1.  Viết class và cài phương thức softmax
Trong pytorch, torch.nn.Module là lớp cơ bản để từ đó xây dựng lên các mô hình hoặc các phương
thức kích hoạt (activation funtion) như sigmoid, softmax,... Trong phần này, chúng ta xây dựng
class Softmax và softmax_stable nhận đầu vào là mảng 1 chiều (tensor 1 chiều) dựa vào kế thừa
từ lớp Module và ghi đè vào phương thức forward() theo công thức sau đây:
![](https://drive.google.com/uc?export=view&id=1gR3s_bAdqxD1FbBS1AsYcHWi68hg7UUs)

In [ ]:
import torch
import torch.nn as nn
class Softmax(nn.Module):
  def __init__(self):
    super(Softmax, self).__init__()
  def forward(self, x):
    return torch.exp(x) / torch.sum(torch.exp(x), dim=0, keepdim=True)

In [ ]:
# Examples 1
import torch
data = torch.Tensor ([1 , 2 , 3])
softmax = Softmax()
output = softmax(data)
output
#>> tensor ([0.0900 , 0.2447 , 0.6652])

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
import torch
import torch.nn as nn
class softmax_stable(nn.Module):
  def __init__(self):
    super(softmax_stable, self).__init__()
  def forward(self, x):
    max_val = torch.max(x)
    return torch.exp(x - max_val) / torch.sum(torch.exp(x - max_val), dim=0, keepdim=True)

In [ ]:
import torch

data = torch.Tensor ([1 , 2 , 3])
softmax_stable = softmax_stable()
output = softmax_stable ( data )
output
# >> tensor ([0.0900 , 0.2447 , 0.6652])

tensor([0.0900, 0.2447, 0.6652])

## 2. Một Ward (phường) gồm có name (string) và danh sách của mọi người trong Ward.
* Một người person có thể là student, doctor, hoặc teacher.
* Một student gồm có name,
yob (int) (năm sinh), và grade (string).
* Một teacher gồm có name, yob, và subject
(string).
* Một doctor gồm có name, yob, và specialist (string). Lưu ý cần sử dụng a
list để chứa danh sách của mọi người trong Ward.
 * (a) Cài đặt các class Student, Doctor, và Teacher theo mô tả trên. Thực hiện phương thức
describe() method để in ra tất cả thông tin của các object.
 * (b) Viết add_person(person) method trong Ward class để add thêm một người mới với nghề
nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một ward
object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra
tên ward (name) và toàn bộ thông tin của từng người trong ward.
 * (c) Viết count_doctor() method để đếm số lượng doctor trong ward.
 * (d) Viết sort_age() method để sort mọi người trong ward theo tuổi của họ với thứ tự tăng dần.
(hint: Có thể sử dụng sort của list hoặc viết thêm function đều được)
 * (e) Viết compute_average() method để tính trung bình năm sinh của các teachers trong ward.

In [ ]:
class Ward:
  def __init__(self, name, people):
    self.name = name
    self.people = people

  def add_person(self, person):
    self.people.append(person)

  def count_doctor(self):
    return sum(isinstance(p, Doctor) for p in self.people)

  def sort_age(self):
    self.people.sort(key=lambda p: p.yob)

  def compute_average(self):
    teachers = [p for p in self.people if isinstance(p, Teacher)]
    if not teachers:
      return None
    return sum(t.yob for t in teachers) / len(teachers)

  def describe(self):
    print(f"Ward: {self.name}")
    for person in self.people:
      person.describe()

class Student:
  def __init__(self, name, yob, grade):
    self.name = name
    self.yob = yob
    self.grade = grade

  def describe(self):
    print(f"Student: {self.name}, yob: {self.yob}, grade: {self.grade}")

class Doctor:
  def __init__(self, name, yob, specialist):
    self.name = name
    self.yob = yob
    self.specialist = specialist

  def describe(self):
    print(f"Doctor: {self.name}, yob: {self.yob}, specialist: {self.specialist}")

class Teacher:
  def __init__(self, name, yob, subject):
    self.name = name
    self.yob = yob
    self.subject = subject

  def describe(self):
    print(f"Teacher: {self.name}, yob: {self.yob}, subject: {self.subject}")


In [ ]:
# ward = Ward("Ward 1", [])

# student = Student("Student 1", 2000, "Grade 1")
# teacher_1 = Teacher("Teacher 1", 1990, "Math")
# teacher_2 = Teacher("Teacher 2", 1985, "Science")
# doctor_1 = Doctor("Doctor 1", 1980, "Cardiologist")
# doctor_2 = Doctor("Doctor 2", 1975, "General")

# ward.add_person(student)
# ward.add_person(teacher_1)
# ward.add_person(teacher_2)
# ward.add_person(doctor_1)
# ward.add_person(doctor_2)
# ward.describe()

In [ ]:
# Examples
# 2(a)
student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
student1.describe()
# output
#>> Student - Name : studentA - YoB : 2010 - Grade : 7



Student:  studentA , yob: 2010, grade: 7


In [ ]:
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher1 . describe ()
# output
# >> Teacher - Name : teacherA - YoB : 1969 - Subject : Math

Teacher:  teacherA , yob: 1969, subject:  Math 


In [ ]:
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")
doctor1 . describe ()
# output
# >> Doctor - Name : doctorA - YoB : 1945 - Specialist : Endocrinologists

Doctor:  doctorA , yob: 1945, specialist:  Endocrinologists 


In [ ]:
# 2(b)
print ()
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward( name =" Ward1 ", people=[])
ward1.add_person ( student1 )
ward1.add_person ( teacher1 )
ward1.add_person ( teacher2 )
ward1.add_person ( doctor1 )
ward1.add_person ( doctor2 )
ward1.describe ()

# output
# >> Ward Name : Ward1
#Student - Name : studentA - YoB : 2010 - Grade : 7
#Teacher - Name : teacherA - YoB : 1969 - Subject : Math
#Teacher - Name : teacherB - YoB : 1995 - Subject : History
#Doctor - Name : doctorA - YoB : 1945 - Specialist : Endocrinologists
#Doctor - Name : doctorB - YoB : 1975 - Specialist : Cardiologists


Ward:  Ward1 
Student:  studentA , yob: 2010, grade: 7
Teacher:  teacherA , yob: 1969, subject:  Math 
Teacher:  teacherB , yob: 1995, subject:  History 
Doctor:  doctorA , yob: 1945, specialist:  Endocrinologists 
Doctor:  doctorB , yob: 1975, specialist:  Cardiologists 


In [ ]:
# 2(c)

print ( f"\ nNumber of doctors : { ward1 . count_doctor ()}")

# output
# >> Number of doctors : 2

\ nNumber of doctors : 2


In [ ]:
# 2(d)
print ("\ nAfter sorting Age of Ward1 people ")
ward1 . sort_age ()
ward1 . describe ()

# output
# >> After sorting Age of Ward1 people
# Ward Name : Ward1
# Student - Name : studentA - YoB : 2010 - Grade : 7
# Teacher - Name : teacherB - YoB : 1995 - Subject : History
# Doctor - Name : doctorB - YoB : 1975 - Specialist : Cardiologists
# Teacher - Name : teacherA - YoB : 1969 - Subject : Math
# Doctor - Name : doctorA - YoB : 1945 - Specialist : Endocrinologists

\ nAfter sorting Age of Ward1 people 
Ward:  Ward1 
Doctor:  doctorA , yob: 1945, specialist:  Endocrinologists 
Teacher:  teacherA , yob: 1969, subject:  Math 
Doctor:  doctorB , yob: 1975, specialist:  Cardiologists 
Teacher:  teacherB , yob: 1995, subject:  History 
Student:  studentA , yob: 2010, grade: 7


In [ ]:
# 2(e)
print ( f"\ nAverage year of birth ( teachers ): { ward1 . compute_average ()}")

# output
# >> Average year of birth ( teachers ) : 1982.0

\ nAverage year of birth ( teachers ): 1982.0


#3.
![](https://drive.google.com/uc?export=view&id=1Q53IohN9WcwF0rZbDgIi5sWdpTSVocgq)

Thực hiện xây dựng class Stack với các phương thức (method) sau đây
* initialization method nhận một input "capacity": dùng để khởi tạo stack với capacity là số lượng element mà stack có thể chứa
* .is_empty(): kiểm tra stack có đang rỗng
* .is_full(): kiểm tra stack đã full chưa
* .pop(): loại bỏ top element và trả về giá trị đó
* .push(value) add thêm value vào trong stack
* .top() lấy giá trị top element hiện tại của stack, nhưng không loại bỏ giá trị đó
* Không cần thiết phải thực hiện với pointer như trong hình minh họa

In [ ]:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def pop(self):
        if self.is_empty():
            print('Do nothing!')
            return None
        else:
            return self.__stack.pop()

    def push(self, value):
        if self.is_full():
            print('Do nothing!')
        else:
            self.__stack.append(value)
    def top(self):
        if self.is_empty():
            print('Do nothing!')
            return None
        else:
            return self.__stack[-1]

In [ ]:
stack1 = MyStack ( capacity =5)
stack1.push(1)
stack1.push(2)
print( stack1.is_full())
# >> False

False


In [ ]:
print ( stack1.top() )
# > >2

2


In [ ]:
print ( stack1.pop() )
# >> 2

2


In [ ]:
print ( stack1.top() )
# >> 1

1


In [ ]:
print ( stack1.pop() )
# >> 1

1


In [ ]:
print ( stack1.is_empty() )
# >> True

True


## 4.
![](https://drive.google.com/uc?export=view&id=1_wtOwWt0OY8KZmyaL63Lovlq3HSTL9An)

Thực hiện xây dựng class Queue với các chức năng (method) sau đây
* initialization method nhận một input "capacity": dùng để khởi tạo queue với capacity là số lượng element mà queue có thể chứa
* .is_empty(): kiểm tra queue có đang rỗng
* .is_full(): kiểm tra queue đã full chưa
* .dequeue(): loại bỏ first element và trả về giá trị đó
* .enqueue(value) add thêm value vào trong queue
* .front() lấy giá trị first element hiện tại của queue, nhưng không loại bỏ giá trị đó
* Không cần thiết phải thực hiện với các pointers như trong hình minh họa

In [ ]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__data = []

    def is_empty(self):
        return len(self.__data) == 0

    def is_full(self):
        return len(self.__data) == self.__capacity

    def dequeue(self):
        if self.is_empty():
            print('Do nothing!')
            return None
        else:
            return self.__data.pop(0)

    def enqueue(self, value):
        if self.is_full():
            print('Do nothing!')
        else:
            self.__data.append(value)

    def print(self):
        print(self.__data)

    def front(self):
        if self.is_empty():
            print('Do nothing!')
            return None
        else:
            return self.__data[0]

In [ ]:
queue1 = MyQueue(capacity =5)

queue1.enqueue(1)

queue1.enqueue(2)

print( queue1.is_full() )
# >> False

False


In [ ]:
print ( queue1.front() )
# >> 1

1


In [ ]:
print ( queue1.dequeue() )
# >> 1

1


In [ ]:
print ( queue1.front() )
# >> 2

2


In [ ]:
print ( queue1.dequeue() )
# >> 2

2


In [ ]:
print ( queue1.is_empty() )
# >> True

True


# Câu hỏi trắc nghiệm

## 1.
Choose c

In [ ]:
import torch
import torch.nn as nn

data = torch.Tensor ([1 , 2 , 3])
softmax_function = nn.Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output[0].item() , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

## 2.
Choose b)

In [ ]:
import torch
import torch . nn as nn

class MySoftmax( nn . Module ) :
  def __init__( self ) :
    super().__init__()

  def forward( self , x ) :
  ### Your Code Here
    return torch.exp(x) / torch.sum(torch.exp(x), dim=0, keepdim=True)
  ### End Code Here

data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

## 3.
Choose c)

In [ ]:
import torch
import torch . nn as nn

class MySoftmax ( nn . Module ) :
  def __init__ ( self ) :
    super () . __init__ ()

  def forward( self , x ) :
  ### Your Code Here
    return torch.exp(x) / torch.sum(torch.exp(x), dim=0, keepdim=True)
  ### End Code Here

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., nan])

## 4
Hoàn thành đoạn code sau đây theo công thức tính stable softmax.
* Choose b)

In [ ]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn.Module ):
  def __init__ ( self ) :
    super().__init__()

  def forward ( self , x ) :
    # max_val = torch.max(x)
    # return torch.exp(x - max_val) / torch.sum(torch.exp(x - max_val), dim=0, keepdim=True)

    x_max = torch.max(x , dim =0 , keepdims = True )
    x_exp = torch.exp (x - x_max.values )
    partition = x_exp.sum(0 , keepdims = True )
    return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output[ -1].item() , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

## 5.
Một người (person) có thể là student, doctor, hoặc teacher. Một student gồm có name(string), yob (int) (năm sinh), và grade (string). Các bạn thực hiện viết class Student theo mô tả trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là gì? Chọn đáp án đúng nhất bên dưới.
* Choose a)

In [ ]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self._name = name
    self._yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Student ( Person ) :
  def __init__ ( self , name :str , yob :int , grade :str) :
    ### Your Code Here
    super().__init__(name, yob)
    self._grade = grade
    ### End Code Here

  def describe ( self ) :
    ### Your Code Here
    print(f"Student: {self._name}, yob: {self._yob}, grade: {self._grade}")
    ### End Code Here

student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1._yob == 2011
student1.describe()

Student:  studentZ2023 , yob: 2011, grade: 6


## 6.
Một người (person) có thể là student, doctor, hoặc teacher. Một teacher gồm có name (string), yob (int), và subject (string). Các bạn thực hiện viết class Teacher theo mô tả trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là gì? Chọn đáp án đúng nhất bên dưới.
* Choose b)

In [ ]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Teacher ( Person ) :
  def __init__ ( self , name :str , yob :int , subject : str) :
  ### Your Code Here
    super().__init__(name, yob)
    self._subject = subject
  ### End Code Here

  def describe ( self ) :
  ### Your Code Here
    print(f"Teacher: {self._name}, yob: {self._yob}, subject: {self._subject}")
 ### End Code Here

teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()

Teacher:  teacherZ2023 , yob: 1991, subject:  History 


## 7.
Một người (person) có thể là student, doctor, hoặc teacher. Một doctor gồm có name(string), yob (string), và specialist (string). Các bạn thực hiện viết class Teacher theo mô tả trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là gì? Chọn đáp án đúng nhất bên dưới.
* Choose a)

In [ ]:
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass


class Doctor ( Person ) :
  def __init__ ( self , name :str , yob :int , specialist :str) :
  ### Your Code Here
    super().__init__(name, yob)
    self._specialist = specialist
  ### End Code Here

  def describe ( self ) :
  ### Your Code Here
    print(f"Doctor: {self._name}, yob: {self._yob}, specialist: {self._specialist}")
  ### End Code Here

doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()

Doctor:  doctorZ2023 , yob: 1981, specialist:  Endocrinologists 


## 8.
Một Ward gồm có name (string) và danh sách của mọi người trong Ward. Một người
person có thể là student, doctor, hoặc teacher và cần sử dụng một list để chứa danh sách của mọingười trong Ward. Viết add_person(person) method trong Ward class để add thêm một người mới với nghề nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một ward object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra tên ward (name) và toàn bộ thông tin của từng người trong ward. Chọn đáp án đúng nhất bên dưới cho phương thức đếm số lượng doctor.
* Choose c)

In [ ]:
class Ward :
  def __init__ ( self , name : str) :
    self . __name = name
    self . __listPeople = list ()

  def add_person ( self , person : Person ) :
    self . __listPeople . append ( person )

  def describe ( self ) :
    print ( f" Ward Name : { self . __name }")
    for p in self . __listPeople :
      p . describe ()

  def count_doctor ( self ) :
  ### Your Code Here
    count = 0
    for p in self.__listPeople:
      if isinstance(p, Doctor):
        count += 1
    return count
  ### End Code Here

student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor1 = Doctor ( name =" doctorA ", yob =1945 , specialist =" Endocrinologists ")
ward1 = Ward ( name =" Ward1 ")
ward1.add_person( student1 )
ward1.add_person( teacher1 )
ward1.add_person( teacher2 )
ward1.add_person( doctor1 )
assert ward1.count_doctor () == 1

doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1.add_person( doctor2 )
ward1.count_doctor()

2

## 9.
Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initialization method nhận một input "capacity": dùng để khởi tạo stack với capacity là số lượng element mà stack có thể chứa. .is_full(): kiểm tra stack đã full chưa. .push(value) add thêm value vào trong stack. Kết quả đầu ra là gì?
* Choose b)

In [ ]:
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
  ### Your Code Here
    if self.is_full():
      print('Do nothing!')
    else:
      self.__stack.append(value)
  ### End Code Here

stack1 = MyStack( capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print ( stack1.is_full() )

False


## 10.
Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initialization method nhận một input "capacity", dùng để khởi tạo stack với capacity là số lượng element mà stack có thể chứa. Phương thức is_empty(): kiểm tra stack có đang rỗng. Phương thức is_full(): kiểm tra stack đã full chưa. Phương thức push(value) add thêm value vào trong stack. Phương
thức top() lấy giá trị top element hiện tại của stack, nhưng không loại bỏ giá trị đó. Kết quả đầu ra là gì?

* Choose b)

In [ ]:
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
  ### Your Code Here
    if self.is_full():
      print('Do nothing!')
    else:
      self.__stack.append(value)
  ### End Code Here
  def is_empty ( self ) :
    return len( self . __stack ) == 0

  def top ( self ) :
  ### Your Code Here
    if self.is_empty():
      print('Do nothing!')
      return None
    else:
      return self.__stack[-1]
  ### End Code Here

stack1 = MyStack(capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print ( stack1.top() )

2


## 11.
Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization method nhận một input "capacity", dùng để khởi tạo queue với capacity là số lượng element mà queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value) add thêm value vào trong queue. Kết quả đầu ra là gì?
* Choose a)

In [ ]:
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def enqueue ( self , value ) :
  ### Your Code Here
    if self.is_full():
      print('Do nothing!')
    else:
      self.__queue.append(value)
  ### End Code Here

queue1 = MyQueue ( capacity =5)
queue1.enqueue(1)
assert queue1.is_full () == False
queue1.enqueue(2)
print ( queue1.is_full() )

False


## 12.
Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization method nhận một input "capacity" dùng để khởi tạo queue với capacity là số lượng element mà queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value) add thêm value vào trong queue. Phương thức front() lấy giá trị first element hiện tại của queue,
nhưng không loại bỏ giá trị đó. Kết quả đầu ra là gì?

* Choose d)

In [ ]:
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def isEmpty ( self ) :
    return len( self . __queue ) == 0

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def dequeue ( self ) :
    if self.isEmpty():
      print('Do nothing!')
      return None
    else:
      return self.__queue.pop(0)

  def enqueue ( self , value ) :
    if self.is_full():
      print('Do nothing!')
      return None
    else:
      self.__queue.append(value)

  def front ( self ) :
  ### Your Code Here
    if self.isEmpty():
      print('Do nothing!')
      return None
    else:
      return self.__queue[0]
  ### End Code Here

queue1 = MyQueue ( capacity =5)
queue1.enqueue(1)
assert queue1.is_full () == False
queue1.enqueue(2)
print ( queue1.front() )

1
