[<img src="../images/colab-badge.svg">](https://colab.research.google.com/drive/13v5oMcqg0jc9pzq-g96JH1z7T3zuha64?usp=sharing)

[<img src="https://colab.research.google.com/assets/colab-badge.svg\">](https://colab.research.google.com/drive/13v5oMcqg0jc9pzq-g96JH1z7T3zuha64?usp=sharing)

# I - Bài tập 1 - NumPy cơ bản

### Câu 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
* a

In [ ]:
import numpy as np
arr = np . arange (0 , 10 , 1)
print (arr)

[0 1 2 3 4 5 6 7 8 9]


### Câu 2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True
* d

In [ ]:
arr = np.ones((3 ,3) ) > 0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np . ones ((3 ,3) , dtype = bool )
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np . full ((3 ,3) , fill_value = True , dtype = bool )
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Câu 3: Kết quả của đoạn code sau đây:
```
import numpy as np
arr = np . arange (0 ,10)
print ( arr [ arr %2 == 1])
```
* a

In [ ]:
import numpy as np
arr = np . arange (0 ,10)
print ( arr [ arr %2 == 1])

[1 3 5 7 9]


### Câu 4: Kết quả của đoạn code sau đây:
```
import numpy as np
arr = np . arange (0 ,10)
arr [ arr %2 ==1] = -1
print ( arr )
```
* b

In [ ]:
import numpy as np
arr = np . arange (0 ,10)
arr [ arr %2 ==1] = -1
print ( arr )

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Câu 5: Kết quả của đoạn code sau đây
```
import numpy as np
arr = np . arange (10)
arr_2d = arr . reshape (2 , -1)
print ( arr_2d )
```
* b

In [ ]:
import numpy as np
arr = np . arange (10)
arr_2d = arr . reshape (2 , -1)
print ( arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Câu 6: Kết quả của đoạn code sau đây
```
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )
```
* a

In [ ]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
print(arr1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
print(arr2)
c = np . concatenate ([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print (" Result : \n", c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
 Result : 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Câu 7: Kết quả của đoạn code sau đây
```
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print ("C = ", c )
```
* c

In [ ]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print ("C = ", c )

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Câu 8: Kết quả của đoạn code sau đây
```
import numpy as np
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )
```
* a

In [ ]:
import numpy as np
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


### Câu 9: Kết quả của đoạn code sau đây
```
import numpy as np
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])
```

In [ ]:
import numpy as np
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])

 result  [ 6  9 10]


### Câu 10: Kết quả của đoạn code sau đây
```
import numpy as np

def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )
```
* d

In [ ]:
import numpy as np

def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


### Câu 11: Kết quả của đoạn code sau đây
```
import numpy as np

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])
print (" Result ", np . where (a <b , b , a ) )
```
* a ?
* 6. 7. 9. 8. 9. 7. 5.

In [ ]:
import numpy as np

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print (" Result ", np . where (a <b , b , a ) )

 Result  [6 7 9 8 9 7 5]


# II - Bài tập 2 - Xử lý ảnh

Các câu hỏi phần này giải quyết bài toán chuyển ảnh màu về ảnh xám. Ví dụ được mô tả như hình sau:
<img src = 'https://drive.google.com/uc?id=1vC8Vs4V1b-99YzRqaep2GrTUAhwk6nAZ'>
**Hình 1: Chuyển ảnh màu thành ảnh xám**
Ảnh sẽ được biểu diễn bởi tập các điểm ảnh (Pixel) có giá trị từ 0 đến 255. Ảnh màu sẽ được biểu
diễn thành ma trận có kích thước (Height, Width, Channel); trong đó số Channel là 3 tương ứng là giá
trị biểu diễn cho các kênh màu R-Red, G-Green, B-Blue. Ảnh xám sẽ được biểu diễn thành ma trận
có kích thước (Height, Width). Vì vậy, để chuyển ảnh màu thành ảnh xám, chúng ta sẽ tổng hợp từ 3
kênh màu RGB thành 1 giá trị duy nhất trong khoảng 0 đến 255. Có 3 phương pháp chính để tính giá
trị chuyển đổi:
* Lightness: Tính giá trị trung bình của giá trị lớn nhất và nhỏ nhất cho các kênh màu: ```(max(R,G,B) + min(R,G,B))/2```
* Average: Tính giá trị trung bình của 3 kênh màu: ```(R+G+B)/3```
* Luminosity: Nhân hệ số tương ứng của 3 kênh màu như sau: ```0.21*R + 0.72*G + 0.07*B```

### Câu 12: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Lightness:

Choose a)

```
# Download image
! gdown 1 i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib . image as mpimg
img = mpimg . imread (’/ content /dog. jpeg ’)
gray_img_01 = # Your Code Here
gray_img_01 [0 , 0]
```

In [2]:
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB



Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 65.0MB/s]


169.5

In [7]:
import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (img.max(axis=2) + img.min(axis=2))/2
gray_img_01[0, 0]

102.5

### Câu 13: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Average:

Choose a)

```
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib . image as mpimg
img = mpimg . imread ('/content/dog.jpeg')
gray_img_02 = # Your Code Here
gray_img_02 [0 , 0]
```

In [5]:
import matplotlib . image as mpimg
img = mpimg . imread ('/content/dog.jpeg')
gray_img_02 = img.mean(axis=2)
gray_img_02 [0 , 0]

107.66666666666667

### Câu 14: Hoàn thành đoạn code sau đây để chuyển ảnh màu sang ảnh xám dựa vào phương pháp Luminosity:

Choose c)

```
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg . imread ('/content/dog.jpeg')
gray_img_03 = # Your Code Here
gray_img_03 [0 , 0]
```

In [6]:
import matplotlib.image as mpimg
img = mpimg . imread ('/content/dog.jpeg')
gray_img_03 = 0.21*img[:,:,0] + 0.72*img[:,:,1] + 0.07*img[:,:,2]
gray_img_03 [0 , 0]

126.22999999999999

# III - Bài tập 3: Phân tích dữ liệu dạng bảng
Các câu hỏi phần này ứng dụng numpy trong phân tích dữ liệu dạng bảng, được mô tả gồm các cột và một số hàng như sau:
<img src='https://drive.google.com/uc?id=1E0vZ0AXdoGiiMOlkVhQvtFmo_2fEAq6k'>
**Hình 2: Dữ liệu Advertising dạng bảng.**

Dựa vào đoạn code sau để tải về dữ liệu và thực hiện các đoạn code cho các các câu hỏi sau để chọn đáp án đúng:
```
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd . read_csv ('/content/advertising.csv')

data = df . to_numpy ()
```

In [8]:
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 12.6MB/s]


In [9]:
import pandas as pd
df = pd . read_csv ('/content/advertising.csv')

data = df . to_numpy ()

### Câu hỏi 15:
Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales

Choose c)

In [14]:
import numpy as np
max_sales_index = np.argmax(data[:,3])
max_sales_value = data[max_sales_index,3]
print(max_sales_index, max_sales_value)

175 27.0


### Câu hỏi 16:
Giá trị trung bình của cột TV là

Choose b)

In [16]:
import numpy as np
tv_avg = np.mean(data[:,0])
print(tv_avg)

147.0425


### Câu hỏi 17:
Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:

Choose a)

In [17]:
import numpy as np
count = np.count_nonzero(data[:,3]>=20)
print(count)

40


### Câu hỏi 18:
Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15:

Choose b)

In [18]:
import numpy as np
radio_avg = np.mean(data[data[:,3]>=15,1])
print(radio_avg)

26.22293577981651


### Câu hỏi 19:
Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper:

Choose c)

In [19]:
import numpy as np
sales_sum = np.sum(data[data[:,2]>np.mean(data[:,2]),3])
print(sales_sum)

1405.1


### Câu hỏi 20:
Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]

Choose c)

In [30]:
data[7:10]

array([[120.2,  19.6,  11.6,  13.2],
       [  8.6,   2.1,   1. ,   4.8],
       [199.8,   2.6,  21.2,  15.6]])

In [31]:
import numpy as np
sales_avg = np.mean(data[:,3])
print(sales_avg)
scores = np.where(data[:,3]>sales_avg, 'Good', np.where(data[:,3]<sales_avg, 'Bad', 'Average'))
scores[7:10]

15.130500000000001


array(['Bad', 'Bad', 'Good'], dtype='<U7')

### Câu hỏi 21:
Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu
giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]

Choose c)

In [29]:
import numpy as np

sales = data[:, 3]

average_sales = np.mean(sales)
print(average_sales)
closest_to_average = sales[np.abs(sales - average_sales).argmin()]
print(closest_to_average)

scores = np.where(sales > closest_to_average, 'Good',
                 np.where(sales < closest_to_average, 'Bad', 'Average'))

scores[7:10]

15.130500000000001
15.2


array(['Bad', 'Bad', 'Good'], dtype='<U7')