**Bài tập 1 (kỹ thuật đọc và xử lý dữ liệu từ file .csv):**

Cho trước file dữ liệu advertising.csv, hãy hoàn
thành function load_data_from_file() trả về dữ liệu đã được tổ chức (features_X cho input và
sales_Y cho output).

In [4]:
#https://drive.google.com/file/d/1r2Sb4ogBjRR1Wu28gy9X2D4WmOdFoICT/view?usp=sharing
!gdown 1r2Sb4ogBjRR1Wu28gy9X2D4WmOdFoICT

Downloading...
From: https://drive.google.com/uc?id=1r2Sb4ogBjRR1Wu28gy9X2D4WmOdFoICT
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.2MB/s]


In [5]:
import numpy as np
# from numpy import genfromtxt
import matplotlib.pyplot as plt
import random
random.seed(0) # please do not remove this line
%matplotlib inline

def load_data_from_file(fileName = "advertising.csv"):
  data = np.genfromtxt(fileName, dtype=None, delimiter=',', skip_header=1)
  features_X = data[:, :3]
  sales_Y = data[:, 3]

  # **************** your code here ****************


  return features_X, sales_Y


In [6]:
#Question 2
features_X, _ = load_data_from_file()
print(features_X[:5,:])

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]]


In [7]:
#Question 3
_, sales_Y = load_data_from_file()
print(sales_Y.shape)

(200,)


**Bài tập 2 (kỹ thuật khởi tạo giá trị cho từng gene trong chromosome (individual), tạo ra các giá trị ngẫu nhiên cho một cá thể (tham số theta của mô hình)):**

hãy hoàn thiện function create_individual(n,bound) để khởi tạo ngẫu nhiên giá trị của n genes (tham số θi) trong chromosome với giá trị từng gene được khởi tạo [-bound/2, bound/2]

In [13]:
def generate_random_value(bound = 10):
    return (random.random() - 0.5)*bound

def create_individual(n=4, bound=10):

  # **************** your code here ****************
   individual = []
   for _ in range(n):
   # Gọi hàm generate_random_value để tạo giá trị ngẫu nhiên cho mỗi gene
    gene_value = generate_random_value(bound)
    individual.append(gene_value)

    return individual

In [14]:
individual = create_individual()
print(individual)

[3.444218515250481]


**Bài tập 3 (kỹ thuật xây dựng fitness function để đánh giá fitness score cho từng chromosome):**
hãy hoàn thiện function compute_fitness(individual) để tính fitness values của một chromosome bằng cách nghịch đảo giá trị của hàm loss theo công thức fitness = 1 / (loss + 1). Hàm compute_fitness(individual) đánh giá độ tốt của một cá thể. Giá trị càng lớn thì cá thể càng tốt.

In [17]:
def compute_loss(individual):
    #theta = np.array(individual)
    theta = np.reshape(individual, (1, -1))  # Reshape to (1, -1) for flexibility
    y_hat = features_X.dot(theta)
    loss  = np.multiply((y_hat-sales_Y), (y_hat-sales_Y)).mean()
    return loss

def compute_fitness(individual):

    # **************** your code here ****************
    # Tính toán giá trị loss
    loss = compute_loss(individual)
    # Tính toán giá trị fitness dựa trên công thức
    fitness = 1 / (loss + 1)
    return fitness

In [18]:
#question 4
features_X, sales_Y = load_data_from_file()
individual = [4.09, 4.82, 3.10, 4.02]
fitness_score = compute_fitness(individual)
print(fitness_score)

ValueError: shapes (200,3) and (1,4) not aligned: 3 (dim 1) != 1 (dim 0)

**Bài tập 4 (kỹ thuật thực hiện crossover giữa 2 chromosomes:**
hãy hoàn thiện function crossover(individual1,
individual2, crossover_rate = 0.9) để thực hiện crossover giữa 2 individual (chromosome). Bước
này, thực hiện việc lai tạo (trao đổi gen) giữa 2 individual với tỉ lệ crossover_rate

In [12]:
def crossover(individual1, individual2, crossover_rate = 0.9):
    individual1_new = individual1.copy()
    individual2_new = individual2.copy()


   # **************** your code here ****************


    return individual1_new, individual2_new

In [ ]:
#question 5
individual1 = [4.09, 4.82, 3.10, 4.02]
individual2 = [3.44, 2.57, -0.79, -2.41]

individual1, individual2 = crossover(individual1, individual2, 2.0)
print("individual1: ", individual1)
print("individual2: ", individual2)

**Bài tập 5 (kỹ thuật mutation với chromosome): **
hãy hoàn thiện function mutate(individual, muta-
tion_rate = 0.05) để thực hiện việc đột biến cho một cá thể với tỉ lệ đột biến là mutation_rate.

In [ ]:
def mutate(individual, mutation_rate = 0.05):
    individual_m = individual.copy()

    # **************** your code here ****************


    return individual_m

In [ ]:
#Question 6
before_individual = [4.09, 4.82, 3.10, 4.02]
after_individual = mutate(individual, mutation_rate = 2.0)
print(before_individual == after_individual)